services:
  app:
    image: hello-front-dev
    build:
      context: . # El contexto tomará este directorio como el "contexto del build"
      dockerfile: dev.Dockerfile # Esto simplemente le indicará qué dockerfile leer
    volumes:
      - ./:/usr/src/app # La ruta puede ser relativa, por lo que ./ es suficiente para decir "la misma ubicación que el docker-compose.yml"
      - /usr/src/app/node_modules # Ignora node_modules en el host
    ports:
      - 5173:5173
    container_name: hello-front-dev # Esto nombrará el contenedor como hello-front-dev